Repository Tool-daruda/35-APPJAM-SERVER-DARUDA, pull requests merged in 2025-01, with the labels that each got.

#2 Feat/#1
  build.gradle
  src/main/java/com/daruda/darudaserver/global/error/BusinessException.java
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
  src/main/java/com/daruda/darudaserver/global/error/code/SuccessCode.java
  src/main/java/com/daruda/darudaserver/global/error/dto/ErrorResponse.java
  src/main/java/com/daruda/darudaserver/global/error/dto/SuccessResponse.java
  src/main/java/com/daruda/darudaserver/global/handler/GlobalExceptionHandler.java
Labels: feat, 재민

#4 [Chore/#3] S3 연결 및 업로드 및 삭제 로직 구현
  build.gradle
  pngwing.com.png
  src/main/java/com/daruda/darudaserver/global/exception/BusinessException.java
  src/main/java/com/daruda/darudaserver/global/exception/InvalidValueException.java
  src/main/java/com/daruda/darudaserver/global/exception/code/ErrorCode.java
  src/main/java/com/daruda/darudaserver/global/exception/code/SuccessCode.java
  src/main/java/com/daruda/darudaserver/global/exception/dto/ErrorResponse.java
  src/main/java/com/daruda/darudaserver/global/exception/dto/SuccessResponse.java
  src/main/java/com/daruda/darudaserver/global/handler/GlobalExceptionHandler.java
  src/main/java/com/daruda/darudaserver/global/image/entity/Image.java
  src/main/java/com/daruda/darudaserver/global/image/repository/ImageRepository.java
  src/main/java/com/daruda/darudaserver/global/image/service/ImageService.java
  src/main/java/com/daruda/darudaserver/global/infra/S3/AWSConfig.java
  src/main/java/com/daruda/darudaserver/global/infra/S3/S3Service.java
  src/main/resources/application.yml
Labels: feat, chore

#12 [chore] 파일 구조 변경 및 NotFoundException 추가
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
  src/main/java/com/daruda/darudaserver/global/error/code/SuccessCode.java
  src/main/java/com/daruda/darudaserver/global/error/dto/ErrorResponse.java
  src/main/java/com/daruda/darudaserver/global/error/dto/SuccessResponse.java
  src/main/java/com/daruda/darudaserver/global/error/exception/BusinessException.java
  src/main/java/com/daruda/darudaserver/global/error/exception/InvalidValueException.java
  src/main/java/com/daruda/darudaserver/global/error/exception/NotFoundException.java
  src/main/java/com/daruda/darudaserver/global/exception/InvalidValueException.java
  src/main/java/com/daruda/darudaserver/global/handler/GlobalExceptionHandler.java
  src/main/java/com/daruda/darudaserver/global/image/entity/Image.java
  src/main/java/com/daruda/darudaserver/global/image/service/ImageService.java
  src/main/java/com/daruda/darudaserver/global/infra/S3/S3Service.java
Labels: chore

#20 [Feat] 이미지 로직 수정
  src/main/java/com/daruda/darudaserver/global/image/entity/Image.java
  src/main/java/com/daruda/darudaserver/global/image/imageController/imageController.java
  src/main/java/com/daruda/darudaserver/global/image/service/ImageService.java
  src/main/java/com/daruda/darudaserver/global/infra/S3/S3Service.java
Labels: feat

#23 [Feat] 툴 세부정보 조회 API
  src/main/java/com/daruda/darudaserver/domain/community/dto/response/BoardRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/controller/ToolController.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlatformRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/RelatedToolListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/RelatedToolRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolCoreListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolCoreRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDetailGetRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDtoGetRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/License.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Plan.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/RelatedTool.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Tool.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolCore.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolImage.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolKeyword.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolPlatForm.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolVideo.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/PlanRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/RelatedToolRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolCoreRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolImageRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolKeywordRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolPlatFormRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolVideoRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/global/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/daruda/darudaserver/global/common/entity/BaseTimeEntity.java
  src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
Labels: feat, 지원

#27 Feat/#20 카카오로그인 구현
  build.gradle
  src/main/java/com/daruda/darudaserver/DarudaApplication.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/JwtTokenResponse.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/LoginResponse.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/SignUpSuccessResponse.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/UserInfo.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/kakao/KakaoAccount.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/kakao/KakaoTokenResponse.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/kakao/KakaoUserDto.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/kakao/KakaoUserProfile.java
  src/main/java/com/daruda/darudaserver/domain/user/entity/UserEntity.java
  src/main/java/com/daruda/darudaserver/domain/user/entity/enums/Positions.java
  src/main/java/com/daruda/darudaserver/domain/user/entity/enums/SocialType.java
  src/main/java/com/daruda/darudaserver/domain/user/repository/UserRepository.java
  src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/auth/client/KakaoAPiFeignClient.java
  src/main/java/com/daruda/darudaserver/global/auth/client/KakaoFeignClient.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/entity/Token.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/repository/TokenRepository.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java
  src/main/java/com/daruda/darudaserver/global/config/FeignConfig.java
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
  src/main/java/com/daruda/darudaserver/global/error/exception/UnauhtorizedException.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: feat, 재민

#46 [Feat] 게시글 CRUD, 찜하기 구현
  src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/req/BoardCreateAndUpdateReq.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/request/BoardCreateAndUpdateReq.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardScrapRes.java
  src/main/java/com/daruda/darudaserver/domain/community/entity/Board.java
  src/main/java/com/daruda/darudaserver/domain/community/entity/BoardScrap.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardImageRepository.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardImageService.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Plan.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Tool.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/PlanRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/provider/JwtValidationType.java
  src/main/java/com/daruda/darudaserver/global/auth/security/ExceptionHandlerFilter.java
  src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
  src/main/java/com/daruda/darudaserver/global/error/code/SuccessCode.java
  src/main/java/com/daruda/darudaserver/global/error/exception/UnauhtorizedException.java
  src/main/java/com/daruda/darudaserver/global/error/exception/UnauthorizedException.java
Labels: feat, 지원

#52 Feat/#51 댓글 작성 API
  src/main/java/com/daruda/darudaserver/domain/comment/controller/CommentController.java
  src/main/java/com/daruda/darudaserver/domain/comment/dto/request/CreateCommentRequest.java
  src/main/java/com/daruda/darudaserver/domain/comment/dto/response/CreateCommentResponse.java
  src/main/java/com/daruda/darudaserver/domain/comment/entity/CommentEntity.java
  src/main/java/com/daruda/darudaserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
  src/main/java/com/daruda/darudaserver/global/infra/S3/S3Service.java
Labels: feat, 재민

#54 [Feat] 게시글 리스트 조회
  src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/req/BoardCreateAndUpdateReq.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/GetBoardResponse.java
  src/main/java/com/daruda/darudaserver/domain/community/entity/Board.java
  src/main/java/com/daruda/darudaserver/domain/community/entity/BoardScrap.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardImageRepository.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Tool.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolScrap.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/global/common/response/ScrollPaginationCollection.java
  src/main/java/com/daruda/darudaserver/global/error/code/SuccessCode.java
Labels: feat, 지원

#48 Feat/#43 관심있는 툴 조회API
  src/main/java/com/daruda/darudaserver/DarudaApplication.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/ToolScrap.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/FavoriteToolsResponse.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/PagenationDto.java
  src/main/java/com/daruda/darudaserver/domain/user/entity/UserEntity.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/config/PageableConfig.java
Labels: feat, 재민

#63 [Fix] 코리 반영 및 JPQL 수정
  src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/GetBoardResponse.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
Labels: enhancement, 지원

#64 [Feat] Scroll DTO 생성
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/GetBoardResponse.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/global/common/response/ScrollPaginationDto.java
Labels: feat, 지원

#66 #61 [fix] 정렬 기준 추가
  src/main/java/com/daruda/darudaserver/domain/comment/controller/CommentController.java
  src/main/java/com/daruda/darudaserver/domain/comment/dto/response/GetCommentRetrieveResponse.java
  src/main/java/com/daruda/darudaserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDtoGetRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/error/code/SuccessCode.java
Labels: feat, 재민

#67 [Feat] 툴 무한 스크롤 구현
  src/main/java/com/daruda/darudaserver/domain/community/entity/Board.java
  src/main/java/com/daruda/darudaserver/domain/tool/controller/ToolController.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlatformRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/RelatedToolListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/RelatedToolRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolCoreListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolCoreRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDetailGetRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDtoGetRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolListRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolResponse.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolScrapCount.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolScrapRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Plan.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/RelatedTool.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Tool.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/global/common/response/ScrollPaginationCollection.java
  src/main/java/com/daruda/darudaserver/global/handler/ValidatorUtil.java
Labels: feat, 지원

#73 #72 [feat] 회원탈퇴 구현
  src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/error/code/SuccessCode.java
Labels: feat, 재민

#98 Fix/#97
  src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/domain/tool/controller/ToolController.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java
Labels: bug, 재민

#100 #99 [fix] 카테고리 반환 순서 수정
  .gitignore
  pngwing.com.png
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java
  src/main/resources/application.yml
Labels: enhancement, 지원

#102 Fix/#101
  src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlatformRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDetailGetRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/ToolDtoGetRes.java
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Tool.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
  src/main/java/com/daruda/darudaserver/domain/user/service/KakaoService.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
Labels: bug, 재민

#112 Fix/#111
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardRepository.java
  src/main/java/com/daruda/darudaserver/domain/community/repository/BoardScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/tool/repository/ToolScrapRepository.java
  src/main/java/com/daruda/darudaserver/domain/user/entity/UserEntity.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/config/WebConfig.java
Labels: bug, 재민

#113 [Fix] 조회시 스크랩 여부 수정
  src/main/java/com/daruda/darudaserver/domain/community/ValidateBoard.java
  src/main/java/com/daruda/darudaserver/domain/community/controller/BoardController.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java
  src/main/java/com/daruda/darudaserver/domain/community/entity/Board.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java
  src/main/java/com/daruda/darudaserver/domain/user/dto/response/FavoriteBoardsResponse.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
Labels: bug, 지원

#121 [Fix] 로깅 파일 수정
  logs/err_logging.2025-01-21.0
  logs/logging.2025-01-21.0
  src/main/resources/logback-spring.xml
Labels: bug, 지원

#123 [Fix] Tool 플랜 Response 수정
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanListRes.java
Labels: enhancement, 지원

#124 [CICD] 배포하기
  logs/err_logging.2025-01-21.0
  logs/logging.2025-01-21.0
  src/main/java/com/daruda/darudaserver/domain/tool/dto/res/PlanListRes.java
  src/main/resources/logback-spring.xml
Labels: 지원

#127 #126 [fix] log 레벨 수정
  src/main/resources/logback-spring.xml
Labels: bug, 재민

#129 #128 [fix] 이미지 return 값 수정
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
Labels: bug, 재민

#139 #138 [fix] 카테고리 수정
  src/main/java/com/daruda/darudaserver/domain/tool/entity/Category.java
Labels: bug, 재민

#144 #143 [fix] 게시글조회 Response toolId 포함
  src/main/generated/com/daruda/darudaserver/domain/tool/entity/QTool.java
  src/main/java/com/daruda/darudaserver/domain/community/dto/res/BoardRes.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
Labels: bug, 재민

#150 [Fix] 예외처리 수정
  src/main/java/com/daruda/darudaserver/domain/comment/controller/CommentController.java
  src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java
  src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
Labels: bug, 재민

#148 [Fix] 자유 게시글 로고 이미지 수정
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/domain/community/util/ValidateBoard.java
Labels: enhancement

#151 [Fix/#147] 예외처리 세부화
  src/main/java/com/daruda/darudaserver/domain/comment/controller/CommentController.java
  src/main/java/com/daruda/darudaserver/domain/comment/service/CommentService.java
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/domain/community/util/ValidateBoard.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/KakaoController.java
  src/main/java/com/daruda/darudaserver/domain/user/controller/MyPageController.java
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java
  src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/daruda/darudaserver/global/error/code/ErrorCode.java
Labels: enhancement, 재민

#164 #161 [fix] SecurityConfig 수정
  src/main/java/com/daruda/darudaserver/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/daruda/darudaserver/global/config/SecurityConfig.java
Labels: bug, 재민

#187 #185 [fix] 리프레시 토큰 업데이트 로직 수정
  src/main/java/com/daruda/darudaserver/domain/user/service/UserService.java
  src/main/java/com/daruda/darudaserver/global/auth/jwt/service/TokenService.java
Labels: bug, 재민

#190 [Fix] 리스트 조회 수정
  src/main/java/com/daruda/darudaserver/domain/community/service/BoardService.java
  src/main/java/com/daruda/darudaserver/domain/tool/service/ToolService.java
Labels: bug
